# Display
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
WINDOW_RESOLUTION = (WINDOW_WIDTH, WINDOW_HEIGHT)
HALF_WINDOW_WIDTH = WINDOW_WIDTH // 2
HALF_WINDOW_HEIGHT = WINDOW_HEIGHT // 2

FPS = 60

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

# Arena Config
LINE_THICKNESS = 4
CENTER_LINE_THICKNESS = LINE_THICKNESS // 2
ARENA_BORDER_THICKNESS = LINE_THICKNESS * 2
ARENA_LINE_COLOR = WHITE

LEFT_EDGE = LINE_THICKNESS
RIGHT_EDGE = WINDOW_WIDTH - LINE_THICKNESS
TOP_EDGE = LINE_THICKNESS
BOTTOM_EDGE = WINDOW_HEIGHT - LINE_THICKNESS
DEAD_CENTER = (WINDOW_WIDTH//2, WINDOW_HEIGHT//2)
MID_TOP = (WINDOW_WIDTH//2, TOP_EDGE)

# Ball Config
BALL_COLOR = WHITE
BALL_THICKNESS = LINE_THICKNESS * 2

# Paddle Config
PADDLE_COLOR = WHITE
PADDLE_SIZE = 50
PADDLE_THICKNESS = LINE_THICKNESS * 2
PADDLE_OFFSET = 20

# Game Config
WINNING_SCORE = 5
DEFAULT_SPEED = -3

PLAYER_ONE = 1
PLAYER_TWO = 2

DEFAULT_FONT_SIZE = 14
SCOREBOARD_FONT_SIZE = DEFAULT_FONT_SIZE + 6

GAME_NAME = 'Pong'